<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('items')->insert([
            [
                'name' => 'Cargo Vessel 5000 DWT',
                'type' => 'ship',
                'code' => 'SHIP-CARGO-5000',
                'brand' => 'Hyundai Heavy Industries',
                'model' => 'HHI-CV5000',
                'specification' => 'Bulk cargo vessel, steel hull',
                'unit' => 'unit',
                'weight' => 5000000,
                'length' => 120.50,
                'width' => 20.30,
                'height' => 15.80,
                'description' => 'Medium-size cargo vessel for domestic shipping',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Oil Tanker 10000 DWT',
                'type' => 'ship',
                'code' => 'SHIP-TANKER-10000',
                'brand' => 'Daewoo Shipbuilding',
                'model' => 'DSME-OT10000',
                'specification' => 'Double hull oil tanker',
                'unit' => 'unit',
                'weight' => 10000000,
                'length' => 145.00,
                'width' => 23.50,
                'height' => 17.20,
                'description' => 'Oil tanker for fuel transportation',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Container Ship 300 TEUs',
                'type' => 'ship',
                'code' => 'SHIP-CONTAINER-300',
                'brand' => 'Mitsubishi Heavy Industries',
                'model' => 'MHI-CS300',
                'specification' => 'Container vessel with deck cranes',
                'unit' => 'unit',
                'weight' => 7200000,
                'length' => 130.75,
                'width' => 22.10,
                'height' => 16.40,
                'description' => 'Container ship for inter-island routes',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Patrol Boat 45m',
                'type' => 'ship',
                'code' => 'SHIP-PATROL-45',
                'brand' => 'Damen Shipyards',
                'model' => 'DAMEN-4500',
                'specification' => 'High-speed patrol boat',
                'unit' => 'unit',
                'weight' => 1200000,
                'length' => 45.00,
                'width' => 7.50,
                'height' => 6.20,
                'description' => 'Patrol boat for coastal security',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ferry Passenger 500 Pax',
                'type' => 'ship',
                'code' => 'SHIP-FERRY-500',
                'brand' => 'Austal',
                'model' => 'AUSTAL-F500',
                'specification' => 'Aluminium passenger ferry',
                'unit' => 'unit',
                'weight' => 3500000,
                'length' => 85.40,
                'width' => 16.00,
                'height' => 12.30,
                'description' => 'Passenger ferry for regional transport',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fishing Vessel 30 GT',
                'type' => 'ship',
                'code' => 'SHIP-FISH-30GT',
                'brand' => 'Local Shipyard',
                'model' => 'FV-30GT',
                'specification' => 'Fishing vessel with cold storage',
                'unit' => 'unit',
                'weight' => 300000,
                'length' => 24.60,
                'width' => 6.20,
                'height' => 5.10,
                'description' => 'Small-scale fishing vessel',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Landing Craft Tank (LCT)',
                'type' => 'ship',
                'code' => 'SHIP-LCT-1000',
                'brand' => 'PT PAL Indonesia',
                'model' => 'PAL-LCT1000',
                'specification' => 'Landing craft for heavy equipment',
                'unit' => 'unit',
                'weight' => 8000000,
                'length' => 95.00,
                'width' => 18.00,
                'height' => 14.00,
                'description' => 'LCT for logistics and heavy cargo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Research Vessel',
                'type' => 'ship',
                'code' => 'SHIP-RESEARCH-01',
                'brand' => 'Fincantieri',
                'model' => 'RV-EXPLORER',
                'specification' => 'Oceanographic research vessel',
                'unit' => 'unit',
                'weight' => 6000000,
                'length' => 110.30,
                'width' => 19.80,
                'height' => 15.00,
                'description' => 'Research vessel for marine studies',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tug Boat 3200 HP',
                'type' => 'ship',
                'code' => 'SHIP-TUG-3200',
                'brand' => 'Sanmar',
                'model' => 'SANMAR-3200',
                'specification' => 'Harbor tug boat',
                'unit' => 'unit',
                'weight' => 950000,
                'length' => 32.00,
                'width' => 11.80,
                'height' => 6.80,
                'description' => 'Tug boat for port operations',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ro-Ro Vessel',
                'type' => 'ship',
                'code' => 'SHIP-RORO-01',
                'brand' => 'Japan Marine United',
                'model' => 'JMU-RORO',
                'specification' => 'Roll-on/Roll-off cargo vessel',
                'unit' => 'unit',
                'weight' => 9000000,
                'length' => 140.00,
                'width' => 25.00,
                'height' => 18.50,
                'description' => 'Ro-Ro vessel for vehicles and cargo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
